### PR TITLE
Add postgresql support

### PR DESCRIPTION
**Pull request by frankh**

### CODE REVIEW

**Comment by adtac** [comment]
I have no business interfering with your fork (but I wrote Commento, so I hope you'll hear me out), but I just noticed it today: have you considered using the master version? You're currently using the deprecated `v0`, which doesn't have postgresql. The latest [master](https://github.com/adtac/commento) (see [documentation](https://docs.commento.io)) does have Postgres support and *tons* of other features (and security updates).

**Comment by adtac** [comment]
(Sorry, couldn't create an issue.)

**Comment by frankh** [comment]
Hi adtac,

Thanks for commenting, and thanks for writing commento!

Unfortunately the old version is a better fit for our use-case as we don't want authentication, and we want a drop-in replacement for the api

We may move to the new version in the future

**Comment by adtac** [comment]
Ah that's fine, just wanted to mention it. Glad the old version works for you :)

**Comment by MrSaints** [comment]
@adtac Thanks again :)

BTW, we are using custom React components that plug n' play with Commento v0. If you are interested, I think there is potential for us to do some sharing here :)

**Pull request merged**
